version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - './db_data:/var/lib/mysql'
    ports:
      - "<free_port>:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:6.0.0-php8.0-apache
    volumes:
      - './wordpress_data:/var/www/html/'
    ports:
      - "<free_port>:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress